### ISSUE TITLE
Create SpecklePlugin Guide

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleOrg#1]
As requested by @Eckart-S, we should create a guide for creating plugins. It should contain what can be a submodule, info about Speckle*Converter development, info about Interop, info about the UI.

**Comment by didimitrie** [comment]
Since this guide would be .net based, should this happen in the SpeckleCore repo? I can start a wiki there and let things rip...

**Comment by radumg** [comment]
I would say so 👍
We can worry about consolidating all the documentation later (currently in wikis, speckle.works and API website)

**Comment by didimitrie** [comment]
https://github.com/speckleworks/SpeckleCore/wiki/Speckle-Plugin-Basics-with-the-.NET-SDK - it's  a start
