### ISSUE TITLE
Add Contribution Guidelines, Code of Conduct, and issue templates for all repos

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleOrg#3]
Contribution guidelines should make mention of using github issue # in commit and PR message.

**Comment by pearswj** [comment]
Some examples that came out of #4...

* [Node.js](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md) (note, in particular, the "Developer's Certificate of Origin 1.1")
* [Open Source Guide](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines)

**Comment by didimitrie** [comment]
thanks @pearswj !

**Comment by didimitrie** [comment]
check check:
- [x] issue templates
- [x] contributing.md
- [x] code of conduct

I'll bring along  the next nice question: how can we centralise all these, instead  of per-repo? Currently a lot of cmd+c & v sorted it out - we can stick to that, but... the itch to automate is strong!

**Comment by pearswj** [comment]
Hopefully there won’t be many changes to be made too often. If there are then we can write a script.

**Comment by didimitrie** [comment]
of  course, i was joking :D

**Comment by pearswj** [comment]
I never joke about automation.

**Comment by didimitrie** [comment]
i'll flag another issue for my memory: the issue templates and pull request template should have a link to the contribution guidelines. They're rather sidelined now!

**Comment by radumg** [comment]
You can place the contribution and issue templates in the docs folder and Github still picks them up, so....do you think git `sub-module` would work for the docs folder ?
Could help keep it centralised in the `SpeckleOrg` repo and not need scripts :wink:

**Comment by didimitrie** [comment]
too late. fuck it! it's good as it is and i hope not to change those anytime soon.

**Comment by didimitrie** [comment]
ok this thing is ✅
