### ISSUE TITLE
Delete archived repos?

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleOrg#5]
- https://github.com/speckleworks/SpeckleGrasshopper
- https://github.com/speckleworks/SpeckleRhinoConverter
- https://github.com/speckleworks/SpeckleAccountManager
- https://github.com/speckleworks/SpeckleUserDataUtils

they're confusing people apparently, and considering the legwork needed for #3 it might be a good move. up for debate

**Comment by fraguada** [comment]
First thought is yes. Second thought is, wait, isn't this open source? Third thought is, what would it take to make the archives available in a way that makes things less confusing?

What about adding one zip of all of the last version of these to the SpeckleRhino repo? It could go in several places, even a release, or on the wiki?

**Comment by radumg** [comment]
How are they confusing people ? If
- they're clearly marked as archive
- their description is update to also state they're deprecated
- a notice is added to top of `README.md` as well

I would say that's enough effort to make it clear things have moved on elsewhere. Don't see the value in deleting the repos, whereas i see a value in retaining all that **effort** and history public & visible.

Personally, i'd be more confused if a zip of the old one showed up in the current repo as a file or wiki. I do however think it's a good idea to add the last version of them as a **release** to the new repos but also make it clear it's deprecated.

**Comment by didimitrie** [comment]
closing this as we've agreed to keep them
